language: android
android:
    components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    
    # The BuildTools version used by your project
    - build-tools-25.0.3
    
    # The SDK version used to compile your project
    - android-25
    
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26
    
    # Specify at least one system image,
    # if you need to run emulator(2) during yout tests
    - sys-img-armeabi-v7a-android-26
    - sys-img-armeabi-v7a-android-17
    
licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
    - chmod +x gradlew

install:
    sdkmanager --list || true
    sdkmanager --uninstall \"system-images;android-15;default;armeabi-v7a\
    sdkmanager --uninstall \"system-images;android-16;default;armeabi-v7a\
    sdkmanager --uninstall \"system-images;android-17;default;armeabi-v7a\
    sdkmanager --uninstall \"system-images;android-18;default;armeabi-v7a\
    sdkmanager --uninstall \"system-images;android-19;default;armeabi-v7a\
    sdkmanager --uninstall \"system-images;android-21;default;armeabi-v7a\
    sdkmanager --uninstall \"extras;google;google_play_services\
    sdkmanager --uninstall \"extras;android;support\
    sdkmanager --uninstall \"platforms;android-10\
    sdkmanager --uninstall \"platforms;android-15\
    sdkmanager --uninstall \"platforms;android-16\
    sdkmanager --uninstall \"platforms;android-17\
    sdkmanager --uninstall \"platforms;android-18\
    sdkmanager --uninstall \"platforms;android-19\  
    sdkmanager --uninstall \"platforms;android-20\
    sdkmanager --uninstall \"platforms;android-21\
    sdkmanager --uninstall \"build-tools;21.1.2\
    echo yes | sdkmanager \"tools\
    echo yes | sdkmanager \"platforms;android-25\
    echo yes | sdkmanager \"platforms;android-${API}\
    echo yes | sdkmanager \"extras;android;m2repository\
    echo yes | sdkmanager \"extras;google;m2repository\
    echo yes | sdkmanager \"extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2\
    echo yes | sdkmanager \"extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2\
    echo yes | sdkmanager \"$EMULATOR\
    echo no | avdmanager create avd -n acib -k \"$EMULATOR\" -f --abi \"$ABI\" --tag \"$TAG\
    emulator -avd acib -engine classic -no-window -camera-back none -camera-front none -verbose -qemu -m 512 & adb wait-for-device get-serialno",
    cd ${TRAVIS_BUILD_DIR}/${DIR} && ./gradlew --version
    cd ${TRAVIS_BUILD_DIR}/${DIR} && ./gradlew clean build
    sdkmanager --list || true